# Generated by Django 4.0.6 on 2022-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ch', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
